spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12755158
    username: sql12755158
    password: Q1APd67sV6

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        hqls: true


jwt:
  signerKey: "FsE+3hsTmHNHMhi2MPUTX8KSGsGtKoLyPoceeVMXjnsvhqR50zet4S63FDTgeOQA"